### ISSUE TITLE
点击首页或者log时 跳转异常

### ISSUE THREAD

**Issue by iRubbish** [jiewenhuang/halo-theme-macwen#2]
![image](https://github.com/jiewenhuang/halo-theme-macwen/assets/32736415/071c807e-9808-43a9-b537-a881c2f9c34f)
![image](https://github.com/jiewenhuang/halo-theme-macwen/assets/32736415/bbd2bd96-f5ee-4328-a5fb-ab96424472b8)

**Comment by jiewenhuang** [comment]
这个是根据[siteUrl](https://docs.halo.run/developer-guide/theme/global-variables#:~:text=%E5%89%AF%E6%A0%87%E9%A2%98%0A%20%20%22-,url,-%22%3A%20%22string)生成的，应该不会有错

**Comment by iRubbish** [comment]
感谢大佬解答，等大佬更加完善再来
目前已更换 wordpress用的开心版的主题
