### ISSUE TITLE
「bug」顶部菜单无修改地方

### ISSUE THREAD

**Issue by iRubbish** [jiewenhuang/halo-theme-macwen#3]
![image](https://github.com/jiewenhuang/halo-theme-macwen/assets/32736415/4f53449c-3d2d-4441-b265-1eaa97156bec)
这一处未找到修改地方，并且根据大大的网站发现都是同一个界面。

**Comment by jiewenhuang** [comment]
已修改为可选菜单，下载最新code更新即可
